### ISSUE TITLE
建议修改一下目录结构

### ISSUE THREAD

**Issue by zgq354** [volio/DPlayer-for-typecho#1]
把.git放在plugins目录下的话开发多个插件的时候就冲突了=_=

我是这个插件的作者
https://github.com/zgq354/APlayer-Typecho-Plugin

(最初我因为不想别人下载解压之后因为目录名的问题导致插件出错所以就用了这种蛋疼的方式，现在发现其实这样子会带来更多的麻烦)

**Comment by lyl86** [comment]
已修改，但是.git一般不会放在plugins目录吧

**Comment by zgq354** [comment]
把.git放在plugins目录就成了管理整个插件目录了然后开发新的插件的时候会很蛋疼
