### ISSUE TITLE
偶尔会出现不显示播放器

### ISSUE THREAD

**Issue by wnark** [volio/DPlayer-for-typecho#20]
typecho使用handsome主题，开了腾讯云cdn,偶尔会出现不显示播放器，需要手动刷新一次页面才会显示播放器
火狐f12在不显示播放器时的报错如下：
![不显示](https://user-images.githubusercontent.com/24355466/71390688-3fe3ac00-263c-11ea-8e48-7dd6ca7f3490.PNG)
手动刷新后报错消失：
![手动刷新后](https://user-images.githubusercontent.com/24355466/71390705-4a05aa80-263c-11ea-96a8-c742904e2a7b.PNG)

**Comment by lyl86** [comment]
这个是你博客的 JS 里面 pjax reInitDPlayer 函数调用的问题

**Comment by lyl86** [comment]
本项目最新版已支持 pjax，参考文档使用

**Comment by wnark** [comment]
> 本项目最新版已支持 pjax，参考文档使用

你好，现在还是会偶尔不出现播放器，需要刷新后才会显示。并且f12没报任何错误。。。
出现问题的网页：
https://www.wnark.com/archives/28.html
![捕获.PNG](https://i.loli.net/2020/01/14/46oATZad9LzyXCk.png)

**Comment by lyl86** [comment]
请自行修改主题，在主题pjax完成回调中执行loadDPlayer()
