### ISSUE TITLE
开启PJAX后不加载播放器，需要刷新，请问PJAX回调函数怎么写呢？

### ISSUE THREAD

**Issue by sunpma** [volio/DPlayer-for-typecho#21]
开启PJAX后每次打开网页都不显示播放器，需要手动刷新
请问播放器的PJAX回调函数应该怎么写呢？感谢~~

**Comment by lyl86** [comment]
更新为最新版，pjax 回调中调用 loadDPlayer();

**Comment by sunpma** [comment]
最新的1.1.0版本期用后全是错误提示，Typecho主题是handsome

Notice: Undefined index: autoplay in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 127
Notice: Undefined index: theme in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 128
Notice: Undefined index: loop in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 129
Notice: Undefined index: screenshot in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 130
Notice: Undefined index: lang in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 133
Notice: Undefined index: logo in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 134
Notice: Undefined index: volume in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 135
Notice: Undefined index: type in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 140
Notice: Undefined index: thumbnails in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 141
Notice: Undefined index: maximum in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 148
Notice: Undefined index: user in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 149
Notice: Undefined index: bottom in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 150
Notice: Undefined index: subtitle in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 154
Notice: Undefined index: autoplay in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 127
Notice: Undefined index: theme in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 128
Notice: Undefined index: loop in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 129
Notice: Undefined index: screenshot in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 130
Notice: Undefined index: lang in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 133
Notice: Undefined index: logo in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 134
Notice: Undefined index: volume in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 135
Notice: Undefined index: type in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 140
Notice: Undefined index: thumbnails in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 141
Notice: Undefined index: maximum in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 148
Notice: Undefined index: user in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 149
Notice: Undefined index: bottom in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 150
Notice: Undefined index: subtitle in /www/wwwroot/sunpma.com/usr/plugins/DPlayer/Plugin.php on line 154

**Comment by lyl86** [comment]
php 版本是多少

**Comment by sunpma** [comment]
php7.3

**Comment by lyl86** [comment]
已修复

**Comment by sunpma** [comment]
OK了，没有问题，十分感谢

**Comment by wnark** [comment]
已更新，没问题了。谢谢大佬
