### ISSUE TITLE
m3u8无法播放啊，大佬！

### ISSUE THREAD

**Issue by philboycn** [volio/DPlayer-for-typecho#25]
http://cctvcnch5ca.v.wscdns.com/live/cctv1_2/10793.m3u8

比如这个，大佬能测试下吗？

**Comment by lyl86** [comment]
需要开HLS支持，并且视频需要设置跨域

**Comment by philboycn** [comment]
@volio 大佬，研究两天，没有头绪。能帮帮忙吗？HLS支持已经打开了，跨域要在人家服务器上去，没办法，想办法在自己服务器上用nginx进行反代，也不成功啊，麻烦大佬提醒下解决方案。感谢！

**Comment by philboycn** [comment]
已搞定，感谢老大。
