### ISSUE TITLE
请问如何加入字幕

### ISSUE THREAD

**Issue by shaopak** [volio/DPlayer-for-typecho#26]
尝试在弹幕源一栏添加字幕文件链接，srt、vvt、xml等格式都试过了，但是点确认后却没有正常显示添加文件；又尝试手动添加addition，但是播放时无反应，是不支持字幕还是需要额外添加什么代码呢

**Comment by TinkoLiu** [comment]
webvtt了解一下

**Comment by lyl86** [comment]
[dplayer subtitle="true" subtitleurl="webvtt url"/]

**Comment by shaopak** [comment]
感谢
