### ISSUE TITLE
bilibili视频无法播放

### ISSUE THREAD

**Issue by Leonhzz** [volio/DPlayer-for-typecho#27]
楼主你好我使用bilibili视频链接时，无法正常解析，这点有点可惜。
是否楼主有考虑将这部分补上？
（ps，bilibili虽然无法直接做外链解析，但是通过直接嵌套的方式却可以）所以，是不是能够做某种跳转，间接性达到支持B站的目的？
好吧，在下只有想法，期待Dplayer发展成全能的播放器。
已星
![image](https://user-images.githubusercontent.com/53173411/81791408-46b28300-9539-11ea-8c56-926883f99171.png)

**Comment by lyl86** [comment]
外链解析不属于播放器功能范围，故无法支持
