### ISSUE TITLE
DPlayer插件在Windows浏览器访问时貌似不能播放带token鉴权的直链，安卓端正常

### ISSUE THREAD

**Issue by wnark** [volio/DPlayer-for-typecho#28]
博客因为更换对象存储，原链接太多不想改，所以用了302跳转，但是我发现视频不能正常播放，如果是使用VLC的话能正常跳转：

有兴趣可以试试

**Comment by wnark** [comment]
还不支持带token的直链 ，不能防盗链。。。。

**Comment by volio** [comment]
这个去 dplayer 主仓库问一下吧

**Comment by lyl86** [comment]
没有配置跨域CORS头的问题，与302无关

**Comment by wnark** [comment]
> 没有配置跨域CORS头的问题，与302无关

302确实支持，抱歉没测试好。
只不过关于带token的直链，在电脑端确实不支持，在手机端支持。
比如我这个
在Windows上无法播放，但在手机上可以正常播放，请问问题出在哪呢？
测试用直链，大佬可以试试看：

**Comment by wnark** [comment]
我看浏览器报错是跨域CORS问题，只不过为啥手机端可以正常播放。。。

**Comment by lyl86** [comment]
chrome 跟 edge 实测正常播放

**Comment by wnark** [comment]
> chrome 跟 edge 实测正常播放

(因为我网盘加了跨域白名单了，目前只对我自己的域名白名单，那个直链你可以加自己博客的dplayer试试)

**Comment by wnark** [comment]
我现在把跨域白名单关了，现在可以复现了
在安卓端的chrome可以播放（打开时间有些长但确实可以开），在Windows的chrome不能播放
就是我的这个博客
或者我朋友的博客：

都可以复现
安卓端的chrome忽略了防跨域还是怎么实现可以播放的呀

**Comment by lyl86** [comment]
安卓原生支持hls视频解析，pc浏览器通过mse解析。本issue的问题是浏览器的实现问题，与本repo无关，如果还有其他问题欢迎 telegram 联系我 https://t.me/volio_mono

**Comment by wnark** [comment]
> 安卓原生支持hls视频解析，pc浏览器通过mse解析。本issue的问题是浏览器的实现问题，与本repo无关，如果还有其他问题欢迎 telegram 联系我 https://t.me/volio_mono

原来如此，谢谢大佬
