### ISSUE TITLE
hls 流媒体无法自动播放

### ISSUE THREAD

**Issue by sbwml** [volio/DPlayer-for-typecho#30]
RT

**Comment by lyl86** [comment]
插件中hls支持需要开启

**Comment by sbwml** [comment]
> 插件中hls支持需要开启

插件已经开启了hls 支持的了

以下是我的页面播放连接
https://www.cooluc.com/%E6%B9%96%E5%8D%97%E5%8D%AB%E8%A7%86.html


插入的视频代码是

`[dplayer url="https://live.cooluc.com/2/10024/index.m3u8?virtualDomain=zjhs.live_hls.zte.com" pic="" autoplay="true"/]`

但是它依然无法自动播放，不知道具体原因是什么

**Comment by lyl86** [comment]
浏览器禁止自动播放，参考 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by sbwml** [comment]
> 浏览器禁止自动播放，参考 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

原来如此！

另外我遇到一个非常奇怪的问题，我在Windows 10 或者 安卓系统上播放 hls 直播是正常的，在 iPhone & iPad 上通过DPlayer组件播放 hls 都是显示加载失败，iOS12  13  14 均播放失败，这大概是iOS系统问题还是我配置过程出差错？😂

补充：iOS上使用  safari、chrome 均表现为加载失败

**Comment by sbwml** [comment]
> > 浏览器禁止自动播放，参考 https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
> 
> 原来如此！
> 
> 另外我遇到一个非常奇怪的问题，我在Windows 10 或者 安卓系统上播放 hls 直播是正常的，在 iPhone & iPad 上通过DPlayer组件播放 hls 都是显示加载失败，iOS12 13 14 均播放失败，这大概是iOS系统问题还是我配置过程出差错？😂
> 
> 补充：iOS上使用 safari、chrome 均表现为加载失败

问题解决了，iOS无法播放是因为推流编码格式缘故，iOS上只支持 .m3u8 utf-8编码格式，之前使用 .m3u latin-1 编码所以导致了播放失败。
