### ISSUE TITLE
怎么才能让它在 Typecho 的评论上也生效？

### ISSUE THREAD

**Issue by sbwml** [volio/DPlayer-for-typecho#32]
怎么才能让它在 Typecho 的评论上也支持  [dplayer url="" pic=""/]  标签？

**Comment by sunpma** [comment]
同问，试了下，好像怎么弄都不行啊~~

**Comment by lyl86** [comment]
在Plugin.php的第24行后添加一行
`Typecho_Plugin::factory('Widget_Abstract_Comments')-> contentEx = ['DPlayer_Plugin', 'replacePlayer'];`

**Comment by sunpma** [comment]
> 在Plugin.php的第24行后添加一行
> `Typecho_Plugin::factory('Widget_Abstract_Comments')-> contentEx = ['DPlayer_Plugin', 'replacePlayer'];`

主题handsome，PHP7.4，评论允许使用的HTML标签和属性已添加`[dplayer url="" pic=""/]`属性
但还是不起作用，使用 `!!!` `!!!` 包裹也不行，无法加载播放器~
