### ISSUE TITLE
需要刷新才能显示视频

### ISSUE THREAD

**Issue by Jiu-xiao** [volio/DPlayer-for-typecho#33]
我在我的typecho博客上使用DPlayer播放视频，但是必须要在文章页面刷新一次才能出现播放框

**Comment by lyl86** [comment]
same #21

**Comment by Jiu-xiao** [comment]
但是我使用的是最新版本1.1.0，仍然有这个问题

**Comment by lyl86** [comment]
pjax 回调中调用 loadDPlayer();
