### ISSUE TITLE
貌似不能解析B站直链

### ISSUE THREAD

**Issue by noisky** [volio/DPlayer-for-typecho#4]
RT.

**Comment by lyl86** [comment]
Bilibili 直链解析目前插件没有实现，可以使用第三方的API例如 [Bilibili danmaku and video link](https://dplayer.js.org/docs/#/?id=bilibili-danmaku-and-video-link)

**Comment by noisky** [comment]
API 难道只用来解析视频的播放地址。。
表示太笨了 不知道怎么直接链接 bilibili 的视频 简直笨死了
我用以下两种方式都无法播放
[[dplayer url=”https://api.prprpr.me/dplayer/video/bilibili?aid=7276963″ danmu=”true”/]]
[[dplayer bilibili="av7276963" danmu="true" /]]
麻烦大佬给个 Typecho 的范例

**Comment by lyl86** [comment]
抱歉刚刚看了一下发现他这个没有直接跳转到视频地址，稍等我联系一下 DIYgod 看能不能加个参数直接跳转到视频地址

**Comment by noisky** [comment]
麻烦大佬了 很喜欢您的播放器

**Comment by lyl86** [comment]
经测试，B站 flv 格式的视频 CORS 头只有 http://www.bilibili.com 导致无法播放，mp4 格式视频如果没有防盗链应该可以播放，但是解析需要自己来写。

我这里简单写了一个 [bilibili.php](https://gist.github.com/volio/788d6ff6366960df981a311a5fdb3bd4) 但是不保证稳定解析，你可以试一下。

**Comment by noisky** [comment]
大佬 能简单的举个例子这个怎么用吗 表示太笨了不会用
https://api.ffis.me/bilibili.php?aid=6462513&q=2

**Comment by lyl86** [comment]
用法是对的，主要是 curl 的一些参数需要调整一下来模拟浏览器访问之类的，我写的这个应该没有完整模拟，你可以自己调整一下 request 函数试下。
